# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ondřej Polanský, poslanec parlamentu ČR | Česká pirátská strana
author: Ondřej Ppolanský
email: polanskyo@psp.cz
description: > # this means to ignore newlines until "baseurl:"
  Zápisník pirátského poslance Ondřeje Polanského.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://opolansky.github.io" # the base hostname & protocol for your site, e.g. http://example.com
keywords: Ondřej Planský, piráti, opensource, big data, doprava, svoboda, eu, ostrava, sněmovna, poslanec
twitter_username: andy_cz
github_username:  opolansky
facebook_username: ondrej.polansky
cover_image: /assets/img/hlavni.jpg
img: /assets/img/hlavni.jpg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock


paginate_path: "/stranka/:num/"
paginate: 5
excerpt_separator: <!--more-->
